In [1]:
import pandas as pd
import numpy as np

file_path = r"C:\Users\deqin\Downloads\MATCAD_Energy_Age_Denkmal_PopPressure_Abriss.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
df.head()

C:\Users\deqin\AppData\Local\Temp\ipykernel_476\398303894.py:6: DtypeWarning: Columns (103,104,107,113,114,115,116) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Dataset shape: (327296, 118)

,bldg_gmlid,AGS,bldg_area,bldg_volume,bldg_function,BtySetID,BtyID,BtySig,Mat_Sum,Mat_ConNrm,...,index_right,latitude,longitude,match_distance_m,number,status,status_raw,title,use,reporting_of_demolition
0,DEBE10YYW00002xf,11000000,10434.53,78359.13,31001_2054,4.0,157,TRD,35189.650,17903.029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
1,DEBE09YYP0003eLR,11000000,836.77,13304.39,31001_1010,4.0,246,MFH,6182.778,2697.168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
2,DEBE05YYR0000Iro,11000000,7.38,17.86,31001_1000,4.0,159,NAS,14.562,9.922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
3,DEBE10YYX00004Df,11000000,8.19,24.45,31001_1010,4.0,159,NAS,19.938,13.584,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
4,DEBE09YYP0000DVt,11000000,6.19,26.43,31001_1010,4.0,159,NAS,21.550,14.684,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported

In [2]:
# Create a stable sequential ID for every polygon/building record
df.insert(0, "building_serial_id", range(1, len(df) + 1))

print("Dataset shape:", df.shape)
print(df[["building_serial_id"]].head())
print(df[["building_serial_id"]].tail())

Dataset shape: (327296, 119)
   building_serial_id
0                   1
1                   2
2                   3
3                   4
4                   5
        building_serial_id
327291              327292
327292              327293
327293              327294
327294              327295
327295              327296

In [3]:
age_related_cols = [
    "freistehen",
    "anderertyp",
    "doppelhaus",
    "gereihtes",
    "x_bis_1900",
    "x1901_1910",
    "x1911_1920",
    "x1921_1930",
    "x1931_1940",
    "x1941_1950",
    "x1951_1960",
    "x1961_1970",
    "x1971_1980",
    "x1981_1990",
    "x1991_2000",
    "x2001_2010",
    "x2011_2015",
    "ueberw_dekade_woh_neu",
    "ew2015",
    "typ",
    "typklar"
]

# Check which expected columns are present
missing_cols = [col for col in age_related_cols if col not in df.columns]

print("Missing expected columns:", missing_cols)
print("\nAvailable relevant columns:")
print([col for col in age_related_cols if col in df.columns])

Missing expected columns: []

Available relevant columns:
['freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'ew2015', 'typ', 'typklar']

In [4]:
# Create a compact inspection table for the relevant columns
age_inspection = pd.DataFrame({
    "dtype": df[age_related_cols].dtypes.astype(str),
    "non_null_count": df[age_related_cols].notna().sum(),
    "null_count": df[age_related_cols].isna().sum(),
    "null_percent": (df[age_related_cols].isna().mean() * 100).round(2),
    "unique_values": df[age_related_cols].nunique(dropna=True)
})

age_inspection

,dtype,non_null_count,null_count,null_percent,unique_values
freistehen,float64,239676,87620,26.77,91
anderertyp,float64,120878,206418,63.07,62
doppelhaus,float64,183200,144096,44.03,60
gereihtes,float64,178380,148916,45.50,110
x_bis_1900,float64,81919,245377,74.97,47
x1901_1910,float64,78883,248413,75.90,37
x1911_1920,float64,93084,234212,71.56,44
x1921_1930,float64,163532,163764,50.04,68
x1931_1940,float64,185816,141480,43.23,76
x1941_1950,float64,92620,234676,71.70,28
x1951_1960,float64,167912,159384,48.70,71
x1961_1970,float64,164177,163119,49.84,68
x1971_1980,float64,169894,157402,48.09,60
x1981_1990,float64,165432,161864,49.45,71
x1991_2000,float64,179722,147574,45.09,72
x2001_2010,float64,146945,180351,55.10,65
x2011_2015,object,89853,237443,72.55,48
ueberw_dekade_woh_neu,object,277132,50164,15.33,14
ew2015,float64,276924,50372,15.39,1377
typ,float64,277132,50164,15.33,46
typklar,object,277132,50164,15.33,46

In [5]:
object_cols_to_inspect = [
    "x2011_2015",
    "ueberw_dekade_woh_neu",
    "typklar"
]

for col in object_cols_to_inspect:
    print("\n" + "=" * 80)
    print(f"COLUMN: {col}")
    print("Number of unique non-null values:", df[col].nunique(dropna=True))
    print("\nValue counts:")
    print(df[col].value_counts(dropna=False).head(60))

================================================================================
COLUMN: x2011_2015
Number of unique non-null values: 48

Value counts:
x2011_2015
NaN      237443
1 - 3     71943
4          4833
5          2540
6          1547
8          1059
7           965
9           705
10          679
11          441
13          347
14          315
45          284
30          283
19          229
12          190
174         182
32          175
20          168
82          163
16          162
18          160
40          157
154         154
22          148
44          139
92          137
25          137
24          130
21          122
46          121
33          119
49          116
29          108
23          103
26           94
17           79
27           71
31           66
56           58
55           57
41           57
52           54
53           51
43           47
39           47
28           41
15           35
35           35
Name: count, dtype: int64

================================================================================
COLUMN: ueberw_dekade_woh_neu
Number of unique non-null values: 14

Value counts:
ueberw_dekade_woh_neu
NaN                          50164
1991-2000                    44399
1931-1940                    42428
1971-1980                    28485
1921-1930                    22959
1961-1970                    21780
gemischte Baualtersklasse    21188
1981-1990                    20825
2001-2010                    19932
bis 1900                     17543
1951-1960                    15476
1901-1910                    10891
2011-2015                     5943
1911-1920                     3296
1941-1950                     1987
Name: count, dtype: int64

================================================================================
COLUMN: typklar
Number of unique non-null values: 46

Value counts:
typklar
Freistehende Einfamilienhäuser mit Garten                                                                    132370
NaN                                                                                                           50164
Reihen- und Doppelhäuser mit Garten                                                                           28043
Villen und Stadtvillen mit parkartigem Garten (überwiegend 1870er-1945)                                       14803
Geschlossene Blockbebauung, Hinterhof (1870er-1918), 5-geschossig                                             13730
Freie Zeilenbebauung (1950er-1970er), mit landschaftlichem Siedlungsgrün, 3–6-geschossig                      13659
Verdichtung in Einzelhausgebieten, Mischbebauung mit Gärten und halbprivater Umgrünung (1870er bis heute)      9534
Geschlossene und halboffene Blockbebauung, Schmuck- und Gartenhof (1870er-1918), 4-geschossig                  7700
Blockrandbebauung mit Großhöfen (1920er-1940er), 3–5-geschossig                                                6847
Parallele Zeilenbebauung mit architektonischem Zeilengrün (1920er bis 1930er), 3 – 5-geschossig                6785
Wochenendhäuser und kleingartenartige Gebiete                                                                  6443
Großsiedlungen und Punkthochhäuser (1960er-1980er), 4–11-geschossig                                            6159
Entkernte Blockrandbebauung, Lückenschluss nach 1945                                                           5096
Dörfliche Mischbebauung                                                                                        3693
Gewerbe- und Industriegebiet, großflächiger Einzelhandel, geringe Bebauung                                     3474
Geschosswohnungsbau der 1990er Jahre und jünger (1990er bis heute)                                             3283
Brachfläche                                                                                                    2214
Mischbebauung, halboffener und offener Schuppenhof, 2-4-geschossig                                             2154
Dichte Blockbebauung, geschlossener Hinterhof (1870er-1918), 5-6-geschossig                                    2149
Kleingartenanlage allgemein                                                                                    1416
Mischgebiet ohne Wohngebietscharakter, geringe Bebauung                                                        1367
Krankenhaus                                                                                                     814
Heterogene, innerstädtische Mischbebauung, Lückenschluss nach 1945                                              646
Sicherheit und Ordnung                                                                                          583
Kindertagesstätte                                                                                               428
Neubau-Schule (nach 1945)                                                                                       408
Gewerbe- und Industriegebiet, großflächiger Einzelhandel, dichte Bebauung                                       378
Sportanlage, ungedeckt                                                                                          371
Kerngebiet                                                                                                      360
Verwaltung                                                                                                      348
Altbau-Schule (vor 1945)                                                                                        265
Baumschule/Gartenbau                                                                                            253
Hochschule und Forschung                                                                                        207
Mischgebiet ohne Wohngebietscharakter, dichte Bebauung                                                          198
Grünanlage/Park                                                                                                 182
Sonstige Gemeinbedarfs- und Sondergebiete                                                                       148
Flächen der Ver- und Entsorgung                                                                                 139
Landwirtschaft                                                                                                  133
Wald                                                                                                             76
Parkplatz                                                                                                        72
Sonstige Jugendeinrichtungen                                                                                     58
Kirche                                                                                                           56
Friedhof                                                                                                         28
sonstige Verkehrsflächen (z.B. Verkehrsinseln etc.)                                                              28
Sportanlage, gedeckt                                                                                             23
Bahnhof und Bahnanlage ohne Gleiskörper                                                                           6
Kultur                                                                                                            5
Name: count, dtype: int64

In [6]:
age_count_cols = [
    "x_bis_1900",
    "x1901_1910",
    "x1911_1920",
    "x1921_1930",
    "x1931_1940",
    "x1941_1950",
    "x1951_1960",
    "x1961_1970",
    "x1971_1980",
    "x1981_1990",
    "x1991_2000",
    "x2001_2010",
    "x2011_2015"
]

for col in age_count_cols:
    print("\n" + "=" * 70)
    print(f"{col}")
    print("dtype:", df[col].dtype)
    print("Minimum:", df[col].min() if df[col].dtype != "object" else "object column")
    print("Maximum:", df[col].max() if df[col].dtype != "object" else "object column")
    print("Sample unique values:")
    print(df[col].dropna().unique()[:20])

======================================================================
x_bis_1900
dtype: float64
Minimum: 1.0
Maximum: 65.0
Sample unique values:
[ 3.  1.  2. 12.  4.  6. 14. 16.  5.  8. 40.  7. 10. 47. 38. 13. 65. 18.
 19.  9.]

======================================================================
x1901_1910
dtype: float64
Minimum: 1.0
Maximum: 75.0
Sample unique values:
[ 1.  2.  4. 22.  3.  5.  7. 12.  9.  6.  8. 10. 17. 19. 16. 18. 11. 13.
 15. 14.]

======================================================================
x1911_1920
dtype: float64
Minimum: 1.0
Maximum: 71.0
Sample unique values:
[ 1. 24.  3. 62. 11.  7.  2.  6.  5. 17. 59.  4. 31. 13. 12. 16.  9. 35.
 32. 10.]

======================================================================
x1921_1930
dtype: float64
Minimum: 1.0
Maximum: 111.0
Sample unique values:
[  4.   1.   5.   3.   2.   9.  25.  47.  10.  68.  39. 104.  14.   7.
  67.   6.  11.  24.  26.  38.]

======================================================================
x1931_1940
dtype: float64
Minimum: 1.0
Maximum: 142.0
Sample unique values:
[ 5. 22.  7. 14. 24. 16.  9.  8.  3.  1.  2. 19. 30. 23. 18.  6.  4. 78.
 60. 34.]

======================================================================
x1941_1950
dtype: float64
Minimum: 1.0
Maximum: 45.0
Sample unique values:
[ 2.  1.  3.  4.  7.  5.  9. 22. 11. 20.  6.  8. 14. 10. 15. 19. 29. 17.
 23. 45.]

======================================================================
x1951_1960
dtype: float64
Minimum: 1.0
Maximum: 105.0
Sample unique values:
[ 7.  2.  3.  1.  6.  4.  5. 63.  9. 22. 57. 81. 10. 11. 13. 14. 34.  8.
 25. 50.]

======================================================================
x1961_1970
dtype: float64
Minimum: 1.0
Maximum: 106.0
Sample unique values:
[ 5.  1.  2.  8.  4.  6.  3.  9. 67. 10. 40. 48. 15. 17.  7. 22. 13. 14.
 12. 35.]

======================================================================
x1971_1980
dtype: float64
Minimum: 1.0
Maximum: 101.0
Sample unique values:
[ 8.  3.  6.  2.  1.  7. 14.  5.  4. 23. 27.  9. 11. 10. 17. 19. 12. 21.
 22. 26.]

======================================================================
x1981_1990
dtype: float64
Minimum: 1.0
Maximum: 135.0
Sample unique values:
[ 2.  1.  4.  9.  3. 13. 11.  7.  6.  8. 27. 24.  5. 17. 10. 14. 20. 22.
 15. 19.]

======================================================================
x1991_2000
dtype: float64
Minimum: 1.0
Maximum: 110.0
Sample unique values:
[ 9.  6.  2.  1.  4.  3.  7.  5.  8. 67. 17. 14. 10. 15. 13. 11. 69. 32.
 33. 24.]

======================================================================
x2001_2010
dtype: float64
Minimum: 1.0
Maximum: 98.0
Sample unique values:
[ 3.  5.  1.  2. 12.  8.  4.  7.  6. 14. 57. 23. 10. 33. 37. 13. 51. 11.
 31. 39.]

======================================================================
x2011_2015
dtype: object
Minimum: object column
Maximum: object column
Sample unique values:
['1 - 3' '4' '5' '8' '7' '41' '10' '92' '13' '6' '29' '19' '9' '11' '18'
 '14' '33' '21' '31' '45']

In [7]:
for col in age_count_cols[:-1]:  # exclude x2011_2015 for now
    non_integer_values = df[col].dropna()[
        df[col].dropna() % 1 != 0
    ]

    print(
        f"{col}: "
        f"{len(non_integer_values)} non-integer values"
    )

x_bis_1900: 0 non-integer values
x1901_1910: 0 non-integer values
x1911_1920: 0 non-integer values
x1921_1930: 0 non-integer values
x1931_1940: 0 non-integer values
x1941_1950: 0 non-integer values
x1951_1960: 0 non-integer values
x1961_1970: 0 non-integer values
x1971_1980: 0 non-integer values
x1981_1990: 0 non-integer values
x1991_2000: 0 non-integer values
x2001_2010: 0 non-integer values

In [8]:
x2011_raw = df["x2011_2015"].dropna().astype(str).str.strip()

x2011_numeric_test = pd.to_numeric(
    x2011_raw,
    errors="coerce"
)

non_numeric_x2011 = x2011_raw[
    x2011_numeric_test.isna()
].value_counts()

print("Non-numeric values in x2011_2015:")
print(non_numeric_x2011)

print("\nNumber of distinct non-numeric encodings:",
      len(non_numeric_x2011))

Non-numeric values in x2011_2015:
x2011_2015
1 - 3    71943
Name: count, dtype: int64

Number of distinct non-numeric encodings: 1

In [9]:
# Create a separate dictionary for cleaned age-count columns
age_numeric_cols = {}

# Convert the 12 already-numeric age columns to nullable numeric values
for col in age_count_cols[:-1]:
    age_numeric_cols[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# Handle x2011_2015 separately:
# numeric strings become numbers; "1 - 3" becomes NaN
age_numeric_cols["x2011_2015"] = pd.to_numeric(
    df["x2011_2015"].replace("1 - 3", np.nan),
    errors="coerce"
)

# Convert dictionary to a separate DataFrame
age_counts = pd.DataFrame(age_numeric_cols, index=df.index)

print("Age-count dataframe shape:", age_counts.shape)
print("\nData types:")
print(age_counts.dtypes)

print("\nNon-null counts:")
print(age_counts.notna().sum())

print("\nSpecial x2011_2015 values after cleaning:")
print(age_counts["x2011_2015"].value_counts(dropna=False).head(10))

Age-count dataframe shape: (327296, 13)

Data types:
x_bis_1900    float64
x1901_1910    float64
x1911_1920    float64
x1921_1930    float64
x1931_1940    float64
x1941_1950    float64
x1951_1960    float64
x1961_1970    float64
x1971_1980    float64
x1981_1990    float64
x1991_2000    float64
x2001_2010    float64
x2011_2015    float64
dtype: object

Non-null counts:
x_bis_1900     81919
x1901_1910     78883
x1911_1920     93084
x1921_1930    163532
x1931_1940    185816
x1941_1950     92620
x1951_1960    167912
x1961_1970    164177
x1971_1980    169894
x1981_1990    165432
x1991_2000    179722
x2001_2010    146945
x2011_2015     17910
dtype: int64

Special x2011_2015 values after cleaning:
x2011_2015
NaN     309386
4.0       4833
5.0       2540
6.0       1547
8.0       1059
7.0        965
9.0        705
10.0       679
11.0       441
13.0       347
Name: count, dtype: int64

In [10]:
# Separate copy for mathematical aggregation only
age_counts_for_math = age_counts.fillna(0)

print("Shape:", age_counts_for_math.shape)

print("\nMinimum values across age columns:")
print(age_counts_for_math.min())

print("\nMaximum values across age columns:")
print(age_counts_for_math.max())

print("\nRows with at least one recorded age-period count:",
      (age_counts_for_math.sum(axis=1) > 0).sum())

print("Rows with no usable age-period counts:",
      (age_counts_for_math.sum(axis=1) == 0).sum())

Shape: (327296, 13)

Minimum values across age columns:
x_bis_1900    0.0
x1901_1910    0.0
x1911_1920    0.0
x1921_1930    0.0
x1931_1940    0.0
x1941_1950    0.0
x1951_1960    0.0
x1961_1970    0.0
x1971_1980    0.0
x1981_1990    0.0
x1991_2000    0.0
x2001_2010    0.0
x2011_2015    0.0
dtype: float64

Maximum values across age columns:
x_bis_1900     65.0
x1901_1910     75.0
x1911_1920     71.0
x1921_1930    111.0
x1931_1940    142.0
x1941_1950     45.0
x1951_1960    105.0
x1961_1970    106.0
x1971_1980    101.0
x1981_1990    135.0
x1991_2000    110.0
x2001_2010     98.0
x2011_2015    174.0
dtype: float64

Rows with at least one recorded age-period count: 277015
Rows with no usable age-period counts: 50281

In [11]:
age_counts_for_math["age_total_recorded"] = age_counts_for_math.sum(axis=1)

print("Summary of age_total_recorded:")
print(age_counts_for_math["age_total_recorded"].describe())

print("\nFrequency of total recorded counts:")
print(
    age_counts_for_math["age_total_recorded"]
    .value_counts()
    .sort_index()
    .head(30)
)

print("\nRows with zero recorded age counts:",
      (age_counts_for_math["age_total_recorded"] == 0).sum())

Summary of age_total_recorded:
count    327296.000000
mean         31.507501
std          27.778062
min           0.000000
25%          14.000000
50%          27.000000
75%          42.000000
max         284.000000
Name: age_total_recorded, dtype: float64

Frequency of total recorded counts:
age_total_recorded
0.0     50281
2.0         3
3.0      1730
4.0      2147
5.0      1657
6.0      1726
7.0      1691
8.0      2573
9.0      2390
10.0     3004
11.0     3329
12.0     4325
13.0     3960
14.0     4556
15.0     5396
16.0     5587
17.0     4972
18.0     6589
19.0     6497
20.0     6371
21.0     6502
22.0     6995
23.0     6140
24.0     6463
25.0     7352
26.0     7579
27.0     6827
28.0     6218
29.0     7135
30.0     6920
Name: count, dtype: int64

Rows with zero recorded age counts: 50281

In [12]:
# Count how many age-period categories have recorded values
age_period_cols = age_count_cols

age_counts_for_math["number_of_age_periods"] = (
    age_counts_for_math[age_period_cols] > 0
).sum(axis=1)

print(
    age_counts_for_math["number_of_age_periods"]
    .value_counts()
    .sort_index()
)

number_of_age_periods
0     50281
1     16261
2     17438
3     18383
4     23325
5     28097
6     33507
7     41395
8     43539
9     32143
10    15087
11     5727
12     1967
13      146
Name: count, dtype: int64

In [13]:
# Identify the age-period column with the highest recorded count
dominant_age_col = age_counts_for_math[age_period_cols].idxmax(axis=1)

# Rows with no age information should remain missing
dominant_age_col = dominant_age_col.where(
    age_counts_for_math["age_total_recorded"] > 0,
    np.nan
)

age_counts_for_math["dominant_age_period"] = dominant_age_col

print(
    age_counts_for_math["dominant_age_period"]
    .value_counts(dropna=False)
)

dominant_age_period
NaN           50281
x1931_1940    47403
x1991_2000    45975
x1971_1980    30934
x1921_1930    25543
x1961_1970    23946
x1981_1990    21604
x_bis_1900    20264
x2001_2010    20095
x1951_1960    16697
x1901_1910    12794
x2011_2015     5700
x1911_1920     3912
x1941_1950     2148
Name: count, dtype: int64

In [14]:
age_counts_for_math.drop(
    columns=["dominant_age_period"],
    inplace=True
)

print(age_counts_for_math.columns.tolist())

['x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'age_total_recorded', 'number_of_age_periods']

In [15]:
# Identify the age-period column with the highest recorded count
dominant_age_col = age_counts_for_math[age_period_cols].idxmax(axis=1)

# Rows with no age information should remain missing
dominant_age_col = dominant_age_col.where(
    age_counts_for_math["age_total_recorded"] > 0,
    np.nan
)

age_counts_for_math["dominant_age_period"] = dominant_age_col

print(
    age_counts_for_math["dominant_age_period"]
    .value_counts(dropna=False)
)

dominant_age_period
NaN           50281
x1931_1940    47403
x1991_2000    45975
x1971_1980    30934
x1921_1930    25543
x1961_1970    23946
x1981_1990    21604
x_bis_1900    20264
x2001_2010    20095
x1951_1960    16697
x1901_1910    12794
x2011_2015     5700
x1911_1920     3912
x1941_1950     2148
Name: count, dtype: int64

In [16]:
print("Derived age feature columns:")
print(age_counts_for_math.columns.tolist())

print("\nShape:")
print(age_counts_for_math.shape)

print("\nPreview:")
display(age_counts_for_math.head())

Derived age feature columns:
['x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'age_total_recorded', 'number_of_age_periods', 'dominant_age_period']

Shape:
(327296, 16)

Preview:

,x_bis_1900,x1901_1910,x1911_1920,x1921_1930,x1931_1940,x1941_1950,x1951_1960,x1961_1970,x1971_1980,x1981_1990,x1991_2000,x2001_2010,x2011_2015,age_total_recorded,number_of_age_periods,dominant_age_period
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN
1,0.0,0.0,0.0,4.0,5.0,0.0,7.0,5.0,0.0,0.0,0.0,0.0,0.0,21.0,4,x1951_1960
2,0.0,0.0,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,1,x1931_1940
3,0.0,0.0,0.0,0.0,7.0,2.0,2.0,1.0,0.0,2.0,9.0,3.0,0.0,26.0,7,x1991_2000
4,0.0,0.0,0.0,1.0,14.0,0.0,3.0,0.0,0.0,0.0,6.0,5.0,0.0,29.0,5,x1931_1940

In [17]:
# Maximum age-period count for each record
dominant_age_count = age_counts_for_math[age_period_cols].max(axis=1)

# Share of all recorded buildings belonging to the dominant period
age_counts_for_math["dominant_age_share"] = np.where(
    age_counts_for_math["age_total_recorded"] > 0,
    dominant_age_count / age_counts_for_math["age_total_recorded"],
    np.nan
)

print(age_counts_for_math["dominant_age_share"].describe())

print("\nSample values:")
display(
    age_counts_for_math[
        ["age_total_recorded", "number_of_age_periods",
         "dominant_age_period", "dominant_age_share"]
    ].head(15)
)

count    277015.000000
mean          0.499823
std           0.230732
min           0.125000
25%           0.317073
50%           0.431818
75%           0.647059
max           1.000000
Name: dominant_age_share, dtype: float64

Sample values:

,age_total_recorded,number_of_age_periods,dominant_age_period,dominant_age_share
0,0.0,0,NaN,NaN
1,21.0,4,x1951_1960,0.333333
2,22.0,1,x1931_1940,1.000000
3,26.0,7,x1991_2000,0.346154
4,29.0,5,x1931_1940,0.482759
5,0.0,0,NaN,NaN
6,35.0,6,x1931_1940,0.685714
7,23.0,5,x1931_1940,0.695652
8,10.0,2,x1931_1940,0.900000
9,0.0,0,NaN,NaN
10,49.0,9,x1931_1940,0.489796
11,16.0,4,x1961_1970,0.500000
12,27.0,9,x1931_1940,0.296296
13,0.0,0,NaN,NaN
14,29.0,8,x1981_1990,0.310345

In [18]:
# Readable labels for the dominant age period
dominant_age_labels = {
    "x_bis_1900": "before_1900",
    "x1901_1910": "1901_1910",
    "x1911_1920": "1911_1920",
    "x1921_1930": "1921_1930",
    "x1931_1940": "1931_1940",
    "x1941_1950": "1941_1950",
    "x1951_1960": "1951_1960",
    "x1961_1970": "1961_1970",
    "x1971_1980": "1971_1980",
    "x1981_1990": "1981_1990",
    "x1991_2000": "1991_2000",
    "x2001_2010": "2001_2010",
    "x2011_2015": "2011_2015"
}

age_counts_for_math["dominant_age_period_label"] = (
    age_counts_for_math["dominant_age_period"]
    .map(dominant_age_labels)
)

display(
    age_counts_for_math[
        ["dominant_age_period", "dominant_age_period_label"]
    ].head(15)
)

   dominant_age_period dominant_age_period_label
0                  NaN                       NaN
1           x1951_1960                 1951_1960
2           x1931_1940                 1931_1940
3           x1991_2000                 1991_2000
4           x1931_1940                 1931_1940
5                  NaN                       NaN
6           x1931_1940                 1931_1940
7           x1931_1940                 1931_1940
8           x1931_1940                 1931_1940
9                  NaN                       NaN
10          x1931_1940                 1931_1940
11          x1961_1970                 1961_1970
12          x1931_1940                 1931_1940
13                 NaN                       NaN
14          x1981_1990                 1981_1990

In [19]:
age_counts_for_math = age_counts_for_math.drop(
    columns=["dominant_age_period"]
)

print(age_counts_for_math.columns.tolist())

['x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'age_total_recorded', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label']

In [20]:
dominant_age_midpoint = {
    "before_1900": 1890,
    "1901_1910": 1905,
    "1911_1920": 1915,
    "1921_1930": 1925,
    "1931_1940": 1935,
    "1941_1950": 1945,
    "1951_1960": 1955,
    "1961_1970": 1965,
    "1971_1980": 1975,
    "1981_1990": 1985,
    "1991_2000": 1995,
    "2001_2010": 2005,
    "2011_2015": 2013
}

age_counts_for_math["dominant_age_midpoint"] = (
    age_counts_for_math["dominant_age_period_label"]
    .map(dominant_age_midpoint)
)

display(
    age_counts_for_math[
        ["dominant_age_period_label", "dominant_age_midpoint"]
    ].head(15)
)

   dominant_age_period_label  dominant_age_midpoint
0                        NaN                    NaN
1                  1951_1960                 1955.0
2                  1931_1940                 1935.0
3                  1991_2000                 1995.0
4                  1931_1940                 1935.0
5                        NaN                    NaN
6                  1931_1940                 1935.0
7                  1931_1940                 1935.0
8                  1931_1940                 1935.0
9                        NaN                    NaN
10                 1931_1940                 1935.0
11                 1961_1970                 1965.0
12                 1931_1940                 1935.0
13                       NaN                    NaN
14                 1981_1990                 1985.0

In [21]:
# Midpoint years for each age period
age_period_midpoints = {
    "x_bis_1900": 1890,
    "x1901_1910": 1905,
    "x1911_1920": 1915,
    "x1921_1930": 1925,
    "x1931_1940": 1935,
    "x1941_1950": 1945,
    "x1951_1960": 1955,
    "x1961_1970": 1965,
    "x1971_1980": 1975,
    "x1981_1990": 1985,
    "x1991_2000": 1995,
    "x2001_2010": 2005,
    "x2011_2015": 2013
}

# Weighted average construction year
weighted_age_sum = sum(
    age_counts_for_math[col] * midpoint
    for col, midpoint in age_period_midpoints.items()
)

age_counts_for_math["weighted_average_construction_year"] = np.where(
    age_counts_for_math[age_period_cols].sum(axis=1) > 0,
    weighted_age_sum / age_counts_for_math[age_period_cols].sum(axis=1),
    np.nan
)

display(
    age_counts_for_math[
        [
            "dominant_age_period_label",
            "dominant_age_midpoint",
            "weighted_average_construction_year"
        ]
    ].head(15)
)

,dominant_age_period_label,dominant_age_midpoint,weighted_average_construction_year
0,NaN,NaN,NaN
1,1951_1960,1955.0,1946.904762
2,1931_1940,1935.0,1935.000000
3,1991_2000,1995.0,1971.153846
4,1931_1940,1935.0,1961.206897
5,NaN,NaN,NaN
6,1931_1940,1935.0,1938.714286
7,1931_1940,1935.0,1939.347826
8,1931_1940,1935.0,1938.000000
9,NaN,NaN,NaN
10,1931_1940,1935.0,1947.040816
11,1961_1970,1965.0,1971.250000
12,1931_1940,1935.0,1942.962963
13,NaN,NaN,NaN
14,1981_1990,1985.0,1971.206897

In [22]:
age_counts_for_math["weighted_average_age_2015"] = (
    2015 - age_counts_for_math["weighted_average_construction_year"]
)

age_counts_for_math["dominant_age_2015"] = (
    2015 - age_counts_for_math["dominant_age_midpoint"]
)

display(
    age_counts_for_math[
        [
            "dominant_age_period_label",
            "weighted_average_construction_year",
            "weighted_average_age_2015",
            "dominant_age_2015"
        ]
    ].head(15)
)

,dominant_age_period_label,weighted_average_construction_year,weighted_average_age_2015,dominant_age_2015
0,NaN,NaN,NaN,NaN
1,1951_1960,1946.904762,68.095238,60.0
2,1931_1940,1935.000000,80.000000,80.0
3,1991_2000,1971.153846,43.846154,20.0
4,1931_1940,1961.206897,53.793103,80.0
5,NaN,NaN,NaN,NaN
6,1931_1940,1938.714286,76.285714,80.0
7,1931_1940,1939.347826,75.652174,80.0
8,1931_1940,1938.000000,77.000000,80.0
9,NaN,NaN,NaN,NaN
10,1931_1940,1947.040816,67.959184,80.0
11,1961_1970,1971.250000,43.750000,50.0
12,1931_1940,1942.962963,72.037037,80.0
13,NaN,NaN,NaN,NaN
14,1981_1990,1971.206897,43.793103,30.0

In [23]:
# Earliest and latest represented construction periods

age_presence = age_counts_for_math[age_period_cols] > 0

earliest_period_col = age_presence.replace(
    False, np.nan
).idxmax(axis=1)

latest_period_col = age_presence.iloc[:, ::-1].replace(
    False, np.nan
).idxmax(axis=1)

age_counts_for_math["earliest_age_midpoint"] = (
    earliest_period_col.map(age_period_midpoints)
)

age_counts_for_math["latest_age_midpoint"] = (
    latest_period_col.map(age_period_midpoints)
)

# Set records with no age information to NaN
no_age_data = age_counts_for_math[age_period_cols].sum(axis=1) == 0

age_counts_for_math.loc[no_age_data, [
    "earliest_age_midpoint",
    "latest_age_midpoint"
]] = np.nan

# Temporal range of the represented distribution
age_counts_for_math["age_distribution_range"] = (
    age_counts_for_math["latest_age_midpoint"]
    - age_counts_for_math["earliest_age_midpoint"]
)

display(
    age_counts_for_math[
        [
            "earliest_age_midpoint",
            "latest_age_midpoint",
            "age_distribution_range"
        ]
    ].head(15)
)

C:\Users\deqin\AppData\Local\Temp\ipykernel_476\2146135880.py:5: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  earliest_period_col = age_presence.replace(
C:\Users\deqin\AppData\Local\Temp\ipykernel_476\2146135880.py:9: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  latest_period_col = age_presence.iloc[:, ::-1].replace(

    earliest_age_midpoint  latest_age_midpoint  age_distribution_range
0                     NaN                  NaN                     NaN
1                  1925.0               1965.0                    40.0
2                  1935.0               1935.0                     0.0
3                  1935.0               2005.0                    70.0
4                  1925.0               2005.0                    80.0
5                     NaN                  NaN                     NaN
6                  1905.0               2005.0                   100.0
7                  1925.0               1995.0                    70.0
8                  1935.0               1965.0                    30.0
9                     NaN                  NaN                     NaN
10                 1905.0               1995.0                    90.0
11                 1955.0               1985.0                    30.0
12                 1890.0               1985.0                    95.0
13                    NaN                  NaN                     NaN
14                 1925.0               2005.0                    80.0

In [24]:
print("Main df shape:", df.shape)

print("\nMain dataframe columns:")
print(df.columns.tolist())

Main df shape: (327296, 119)

Main dataframe columns:
['building_serial_id', 'bldg_gmlid', 'AGS', 'bldg_area', 'bldg_volume', 'bldg_function', 'BtySetID', 'BtyID', 'BtySig', 'Mat_Sum', 'Mat_ConNrm', 'Mat_ConLgt', 'Mat_BriBrt', 'Mat_BriIns', 'Mat_ClyRcv', 'Mat_CalMrt', 'Mat_AnhMrt', 'Mat_LoaMrt', 'Mat_SynMrt', 'Mat_CalScr', 'Mat_AnhScr', 'Mat_AnhDsc', 'Mat_SynScr', 'Mat_SlmBri', 'Mat_AcnBlc', 'Mat_ConBlc', 'Mat_MudBri', 'Mat_GpsPlb', 'Mat_MinCnb', 'Mat_MinIns', 'Mat_ConRcv', 'Mat_FcmRcv', 'Mat_SltRcv', 'Mat_OrgSbs', 'Mat_MinFil', 'Mat_MinGls', 'Mat_NatStn', 'Mat_MinOth', 'Mat_TmbSwn', 'Mat_WodPrc', 'Mat_RnwIns', 'Mat_StrRcv', 'Mat_RnwOth', 'Mat_HcbIns', 'Mat_PlaRcv', 'Mat_HcbRcv', 'Mat_BtmRcv', 'Mat_BtmMem', 'Mat_FemRcv', 'Mat_FemOth', 'Mat_NfeAlm', 'Mat_NfeAlu', 'Mat_NfeCpr', 'Mat_NfeOth', 'id', 'gisid', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'overlap_ratio_matcad', 'bbox_length_m', 'bbox_width_m', 'footprint_area_m2', 'height_proxy_m', 'energy_intensity_kwh_m3a', 'denkmal_status', 'index_age', 'age_schluessel', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'ew2015', 'typ', 'typklar', 'building_idx', 'schluessel_2011', 'pop_2011', 'area_ha_2011', 'density_2011', 'overlap_area_m2_2011', 'schluessel_2022', 'pop_2022', 'area_m2_2022', 'density_2022', 'overlap_area_m2_2022', 'density_change', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'address', 'background', 'demolition_year_numeric', 'demolition_year_original', 'description', 'index_right', 'latitude', 'longitude', 'match_distance_m', 'number', 'status', 'status_raw', 'title', 'use', 'reporting_of_demolition']

In [25]:
# Identify material-detail columns
mat_cols = [col for col in df.columns if col.startswith("Mat_")]

print("Material columns to remove:", len(mat_cols))
print(mat_cols)

Material columns to remove: 45
['Mat_Sum', 'Mat_ConNrm', 'Mat_ConLgt', 'Mat_BriBrt', 'Mat_BriIns', 'Mat_ClyRcv', 'Mat_CalMrt', 'Mat_AnhMrt', 'Mat_LoaMrt', 'Mat_SynMrt', 'Mat_CalScr', 'Mat_AnhScr', 'Mat_AnhDsc', 'Mat_SynScr', 'Mat_SlmBri', 'Mat_AcnBlc', 'Mat_ConBlc', 'Mat_MudBri', 'Mat_GpsPlb', 'Mat_MinCnb', 'Mat_MinIns', 'Mat_ConRcv', 'Mat_FcmRcv', 'Mat_SltRcv', 'Mat_OrgSbs', 'Mat_MinFil', 'Mat_MinGls', 'Mat_NatStn', 'Mat_MinOth', 'Mat_TmbSwn', 'Mat_WodPrc', 'Mat_RnwIns', 'Mat_StrRcv', 'Mat_RnwOth', 'Mat_HcbIns', 'Mat_PlaRcv', 'Mat_HcbRcv', 'Mat_BtmRcv', 'Mat_BtmMem', 'Mat_FemRcv', 'Mat_FemOth', 'Mat_NfeAlm', 'Mat_NfeAlu', 'Mat_NfeCpr', 'Mat_NfeOth']

In [26]:
df = df.drop(columns=mat_cols)

print("Updated df shape:", df.shape)
print("Remaining material columns:", [
    col for col in df.columns if col.startswith("Mat_")
])

Updated df shape: (327296, 74)
Remaining material columns: []

In [27]:
df.head(5)

,building_serial_id,bldg_gmlid,AGS,bldg_area,bldg_volume,bldg_function,BtySetID,BtyID,BtySig,id,...,index_right,latitude,longitude,match_distance_m,number,status,status_raw,title,use,reporting_of_demolition
0,1,DEBE10YYW00002xf,11000000,10434.53,78359.13,31001_2054,4.0,157,TRD,a_waermeversorg_gebaeudedaten_2022.G427469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
1,2,DEBE09YYP0003eLR,11000000,836.77,13304.39,31001_1010,4.0,246,MFH,a_waermeversorg_gebaeudedaten_2022.G406691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
2,3,DEBE05YYR0000Iro,11000000,7.38,17.86,31001_1000,4.0,159,NAS,a_waermeversorg_gebaeudedaten_2022.G172069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
3,4,DEBE10YYX00004Df,11000000,8.19,24.45,31001_1010,4.0,159,NAS,a_waermeversorg_gebaeudedaten_2022.G409705,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported
4,5,DEBE09YYP0000DVt,11000000,6.19,26.43,31001_1010,4.0,159,NAS,a_waermeversorg_gebaeudedaten_2022.G361278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_reported

In [28]:
print("Main df shape:", df.shape)

print("\nMain dataframe columns:")
print(df.columns.tolist())

Main df shape: (327296, 74)

Main dataframe columns:
['building_serial_id', 'bldg_gmlid', 'AGS', 'bldg_area', 'bldg_volume', 'bldg_function', 'BtySetID', 'BtyID', 'BtySig', 'id', 'gisid', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'overlap_ratio_matcad', 'bbox_length_m', 'bbox_width_m', 'footprint_area_m2', 'height_proxy_m', 'energy_intensity_kwh_m3a', 'denkmal_status', 'index_age', 'age_schluessel', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'ew2015', 'typ', 'typklar', 'building_idx', 'schluessel_2011', 'pop_2011', 'area_ha_2011', 'density_2011', 'overlap_area_m2_2011', 'schluessel_2022', 'pop_2022', 'area_m2_2022', 'density_2022', 'overlap_area_m2_2022', 'density_change', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'address', 'background', 'demolition_year_numeric', 'demolition_year_original', 'description', 'index_right', 'latitude', 'longitude', 'match_distance_m', 'number', 'status', 'status_raw', 'title', 'use', 'reporting_of_demolition']

In [29]:
# Missing-value audit
missing_audit = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "unique_values": df.nunique(dropna=True)
})

missing_audit = missing_audit.sort_values(
    "missing_pct",
    ascending=False
)

display(missing_audit)

                            dtype  missing_count  missing_pct  unique_values
description                object         327236    99.981668             60
background                 object         327230    99.979835             66
use                        object         327227    99.978918              6
title                      object         327227    99.978918             69
status_raw                 object         327227    99.978918              4
...                           ...            ...          ...            ...
footprint_area_m2         float64              0     0.000000         327275
height_proxy_m            float64              0     0.000000         327295
energy_intensity_kwh_m3a  float64              0     0.000000         321953
denkmal_status               bool              0     0.000000              2
reporting_of_demolition    object              0     0.000000              2

[74 rows x 4 columns]

In [30]:
definitely_drop = [
    "description",
    "background",
    "use",
    "title",
    "status_raw"
]

In [31]:
spatial_artifact_cols = [
    "latitude",
    "longitude",
    "match_distance_m",
    "index_right"
]

In [32]:
cols_to_drop = [
    # Almost entirely empty text/source metadata
    "description",
    "background",
    "use",
    "title",
    "status_raw",

    # Demolition-source metadata
    "number",
    "status",
    "demolition_year_numeric",
    "demolition_year_original",
    "address",

    # Spatial matching artifacts
    "index_right",
    "match_distance_m",
    "latitude",
    "longitude"
]

df = df.drop(columns=cols_to_drop, errors="ignore")

print("Updated df shape:", df.shape)
print("\nRemaining columns:")
print(df.columns.tolist())

Updated df shape: (327296, 60)

Remaining columns:
['building_serial_id', 'bldg_gmlid', 'AGS', 'bldg_area', 'bldg_volume', 'bldg_function', 'BtySetID', 'BtyID', 'BtySig', 'id', 'gisid', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'overlap_ratio_matcad', 'bbox_length_m', 'bbox_width_m', 'footprint_area_m2', 'height_proxy_m', 'energy_intensity_kwh_m3a', 'denkmal_status', 'index_age', 'age_schluessel', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'ew2015', 'typ', 'typklar', 'building_idx', 'schluessel_2011', 'pop_2011', 'area_ha_2011', 'density_2011', 'overlap_area_m2_2011', 'schluessel_2022', 'pop_2022', 'area_m2_2022', 'density_2022', 'overlap_area_m2_2022', 'density_change', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition']

In [33]:
population_intermediate_cols = [
    "building_idx",
    "schluessel_2011",
    "pop_2011",
    "area_ha_2011",
    "density_2011",
    "overlap_area_m2_2011",
    "schluessel_2022",
    "pop_2022",
    "area_m2_2022",
    "density_2022",
    "overlap_area_m2_2022",
    "density_change"
]

df = df.drop(
    columns=population_intermediate_cols,
    errors="ignore"
)

print("Updated df shape:", df.shape)

Updated df shape: (327296, 48)

In [34]:
cols_to_drop = [
    "overlap_ratio_matcad",
    "bbox_length_m",
    "bbox_width_m",
    "footprint_area_m2",
    "height_proxy_m",
    "index_age",
    "age_schluessel",
    "ew2015"
]

df = df.drop(columns=cols_to_drop, errors="ignore")

print("Updated df shape:", df.shape)
print(df.columns.tolist())

Updated df shape: (327296, 40)
['building_serial_id', 'bldg_gmlid', 'AGS', 'bldg_area', 'bldg_volume', 'bldg_function', 'BtySetID', 'BtyID', 'BtySig', 'id', 'gisid', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'typ', 'typklar', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition']

In [35]:
derived_age_cols = [
    "number_of_age_periods",
    "dominant_age_share",
    "dominant_age_period_label",
    "dominant_age_midpoint",
    "weighted_average_construction_year",
    "weighted_average_age_2015",
    "dominant_age_2015",
    "earliest_age_midpoint",
    "latest_age_midpoint",
    "age_distribution_range"
]

print("Derived age columns available:")
print([
    col for col in derived_age_cols
    if col in age_counts_for_math.columns
])

print("\nMissing derived columns:")
print([
    col for col in derived_age_cols
    if col not in age_counts_for_math.columns
])

Derived age columns available:
['number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range']

Missing derived columns:
[]

In [36]:
# Merge selected derived age-context variables into the main dataframe
df = df.join(
    age_counts_for_math[derived_age_cols],
    how="left"
)

print("Updated df shape:", df.shape)
print("\nAdded age-derived columns:")
print(derived_age_cols)

Updated df shape: (327296, 50)

Added age-derived columns:
['number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range']

In [37]:
# Availability of the three main analytical information groups

has_energy = df["energy_intensity_kwh_m3a"].notna()

has_age = df["number_of_age_periods"].gt(0)

has_density_change = df["pop_density_pressure_change"].notna()

availability_audit = pd.DataFrame({
    "has_energy": has_energy,
    "has_age": has_age,
    "has_density_change": has_density_change
})

print("Total records:", len(df))

print("\nIndividual availability:")
display(
    availability_audit.sum().to_frame("records")
)

print("\nIndividual missingness:")
display(
    (~availability_audit).sum().to_frame("records_missing")
)

print("\nCombined availability:")
display(
    availability_audit.value_counts().rename("records").to_frame()
)

Total records: 327296

Individual availability:

                    records
has_energy           327296
has_age              277015
has_density_change   311007

Individual missingness:

                    records_missing
has_energy                        0
has_age                       50281
has_density_change            16289

Combined availability:

                                       records
has_energy has_age has_density_change
True       True    True                 274460
           False   True                  36547
                   False                 13734
           True    False                  2555

In [38]:
# Check reported demolitions against data availability

demolition_check = availability_audit.copy()
demolition_check["reporting_of_demolition"] = df[
    "reporting_of_demolition"
]

display(
    pd.crosstab(
        demolition_check["reporting_of_demolition"],
        [
            demolition_check["has_energy"],
            demolition_check["has_age"],
            demolition_check["has_density_change"]
        ],
        margins=True
    )
)

has_energy                True                          All
has_age                  False         True
has_density_change       False   True False    True
reporting_of_demolition
not_reported             13714  36524  2555  274434  327227
reported                    20     23     0      26      69
All                      13734  36547  2555  274460  327296

In [39]:
positive_cases = df["reporting_of_demolition"].eq("reported")

missingness_by_target = pd.DataFrame({
    "total_records": [
        len(df),
        positive_cases.sum(),
        (~positive_cases).sum()
    ],
    "missing_age": [
        df["number_of_age_periods"].eq(0).sum(),
        (positive_cases & df["number_of_age_periods"].eq(0)).sum(),
        ((~positive_cases) & df["number_of_age_periods"].eq(0)).sum()
    ],
    "missing_density_change": [
        df["pop_density_pressure_change"].isna().sum(),
        (positive_cases & df["pop_density_pressure_change"].isna()).sum(),
        ((~positive_cases) & df["pop_density_pressure_change"].isna()).sum()
    ],
    "complete_age_density": [
        (
            df["number_of_age_periods"].gt(0)
            & df["pop_density_pressure_change"].notna()
        ).sum(),
        (
            positive_cases
            & df["number_of_age_periods"].gt(0)
            & df["pop_density_pressure_change"].notna()
        ).sum(),
        (
            (~positive_cases)
            & df["number_of_age_periods"].gt(0)
            & df["pop_density_pressure_change"].notna()
        ).sum()
    ]
}, index=["all", "reported", "not_reported"])

display(missingness_by_target)

,total_records,missing_age,missing_density_change,complete_age_density
all,327296,50281,16289,274460
reported,69,43,20,26
not_reported,327227,50238,16269,274434

In [40]:
print("Shape:", df.shape)
display(pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str),
    "missing": df.isna().sum().values
}))

Shape: (327296, 50)

,column,dtype,missing
building_serial_id,building_serial_id,int64,0
bldg_gmlid,bldg_gmlid,object,0
AGS,AGS,int64,0
bldg_area,bldg_area,float64,0
bldg_volume,bldg_volume,float64,0
bldg_function,bldg_function,object,0
BtySetID,BtySetID,float64,0
BtyID,BtyID,int64,0
BtySig,BtySig,object,0
id,id,object,0
gisid,gisid,object,0
typ_ist,typ_ist,object,0
typ_mod1,typ_mod1,object,0
k2_w_l,k2_w_l,object,0
nwbz,nwbz,float64,0
energy_intensity_kwh_m3a,energy_intensity_kwh_m3a,float64,0
denkmal_status,denkmal_status,bool,0
freistehen,freistehen,float64,87620
anderertyp,anderertyp,float64,206418
doppelhaus,doppelhaus,float64,144096
gereihtes,gereihtes,float64,148916
x_bis_1900,x_bis_1900,float64,245377
x1901_1910,x1901_1910,float64,248413
x1911_1920,x1911_1920,float64,234212
x1921_1930,x1921_1930,float64,163764
x1931_1940,x1931_1940,float64,141480
x1941_1950,x1941_1950,float64,234676
x1951_1960,x1951_1960,float64,159384
x1961_1970,x1961_1970,float64,163119
x1971_1980,x1971_1980,float64,157402
x1981_1990,x1981_1990,float64,161864
x1991_2000,x1991_2000,float64,147574
x2001_2010,x2001_2010,float64,180351
x2011_2015,x2011_2015,object,237443
ueberw_dekade_woh_neu,ueberw_dekade_woh_neu,object,50164
typ,typ,float64,50164
typklar,typklar,object,50164
pop_density_pressure_change,pop_density_pressure_change,float64,16289
pop_density_pressure_pct_change,pop_density_pressure_pct_change,float64,17969
reporting_of_demolition,reporting_of_demolition,object,0
number_of_age_periods,number_of_age_periods,int64,0
dominant_age_share,dominant_age_share,float64,50281
dominant_age_period_label,dominant_age_period_label,object,50281
dominant_age_midpoint,dominant_age_midpoint,float64,50281
weighted_average_construction_year,weighted_average_construction_year,float64,50281
weighted_average_age_2015,weighted_average_age_2015,float64,50281
dominant_age_2015,dominant_age_2015,float64,50281
earliest_age_midpoint,earliest_age_midpoint,float64,50281
latest_age_midpoint,latest_age_midpoint,float64,50281
age_distribution_range,age_distribution_range,float64,50281

In [41]:
categorical_cols = [
    "bldg_function",
    "BtySig",
    "typ_ist",
    "typ_mod1",
    "k2_w_l",
    "ueberw_dekade_woh_neu",
    "typ",
    "typklar",
    "reporting_of_demolition"
]

for col in categorical_cols:
    print(f"\n{'=' * 70}")
    print(f"{col}")
    print("dtype:", df[col].dtype)
    print("unique values:", df[col].nunique(dropna=False))
    display(df[col].value_counts(dropna=False).head(25))

======================================================================
bldg_function
dtype: object
unique values: 139

bldg_function
31001_1010    268693
31001_1312      8986
31001_1120      8657
31001_1000      6163
31001_2120      3771
31001_2143      3203
31001_2020      3157
31001_2111      2294
31001_3021      1992
31001_2054      1855
31001_3065      1365
31001_2010      1052
31001_2142       965
31001_1022       551
31001_2050       546
31001_2071       544
31001_2081       527
31001_2310       523
31001_3010       515
31001_1130       504
31001_2140       482
31001_3051       454
31001_3211       445
31001_2130       413
31001_3212       403
Name: count, dtype: int64

======================================================================
BtySig
dtype: object
unique values: 11

BtySig
SFH    172854
MFH    104852
NAS     16343
ONR      8724
PRO      7867
OFC      4759
STG      4716
TRD      4294
HSN      1359
HOT      1350
ASB       178
Name: count, dtype: int64

======================================================================
typ_ist
dtype: object
unique values: 5

typ_ist
Wohngebäude - zentrale Versorgung                                 122168
Wohngebäude - dezentrale Versorgung                               118310
Wohngebäude - Übergangsbereich dezentrale/ zentrale Versorgung     53738
Nichtwohngebäude                                                   33079
Wohngebäude - wärmerelevante Wohngebäude ohne Bewertung                1
Name: count, dtype: int64

======================================================================
typ_mod1
dtype: object
unique values: 5

typ_mod1
Wohngebäude - dezentrale Versorgung                               206437
Wohngebäude - zentrale Versorgung                                  85564
Nichtwohngebäude                                                   33079
Wohngebäude - Übergangsbereich dezentrale/ zentrale Versorgung      2215
Wohngebäude - wärmerelevante Wohngebäude ohne Bewertung                1
Name: count, dtype: int64

======================================================================
k2_w_l
dtype: object
unique values: 10

k2_w_l
K10 - Wohngebäude inkl. Mischnutzungen (nachrichtlich, ohne Beurteilung)                    294217
K01 - beheizt                                                                                18457
K03 - geringe Raumsolltemperatur                                                             12165
K04 - teilweise beheizt                                                                       1664
K02 - temporär beheizt                                                                         593
K06 - keine Beurteilung möglich (teilweise beheizte Gebäude in einem Gebäudekonglomerat)        93
K09 - nicht wärmerelevant (Grundfläche unter 50 qm)                                             66
K08 - keine Beurteilung möglich (sonstige Gründe)                                               21
K05 - nicht beheizt                                                                             19
K07 - keine Beurteilung möglich (keine GFK-Zuordnung möglich)                                    1
Name: count, dtype: int64

======================================================================
ueberw_dekade_woh_neu
dtype: object
unique values: 15

ueberw_dekade_woh_neu
NaN                          50164
1991-2000                    44399
1931-1940                    42428
1971-1980                    28485
1921-1930                    22959
1961-1970                    21780
gemischte Baualtersklasse    21188
1981-1990                    20825
2001-2010                    19932
bis 1900                     17543
1951-1960                    15476
1901-1910                    10891
2011-2015                     5943
1911-1920                     3296
1941-1950                     1987
Name: count, dtype: int64

======================================================================
typ
dtype: float64
unique values: 47

typ
23.0    132370
NaN      50164
22.0     28043
24.0     14803
2.0      13730
11.0     13659
25.0      9534
3.0       7700
10.0      6847
72.0      6785
59.0      6443
9.0       6159
7.0       5096
21.0      3693
30.0      3474
73.0      3283
57.0      2214
6.0       2154
1.0       2149
37.0      1416
33.0      1367
46.0       814
8.0        646
41.0       583
47.0       428
Name: count, dtype: int64

======================================================================
typklar
dtype: object
unique values: 47

typklar
Freistehende Einfamilienhäuser mit Garten                                                                    132370
NaN                                                                                                           50164
Reihen- und Doppelhäuser mit Garten                                                                           28043
Villen und Stadtvillen mit parkartigem Garten (überwiegend 1870er-1945)                                       14803
Geschlossene Blockbebauung, Hinterhof (1870er-1918), 5-geschossig                                             13730
Freie Zeilenbebauung (1950er-1970er), mit landschaftlichem Siedlungsgrün, 3–6-geschossig                      13659
Verdichtung in Einzelhausgebieten, Mischbebauung mit Gärten und halbprivater Umgrünung (1870er bis heute)      9534
Geschlossene und halboffene Blockbebauung, Schmuck- und Gartenhof (1870er-1918), 4-geschossig                  7700
Blockrandbebauung mit Großhöfen (1920er-1940er), 3–5-geschossig                                                6847
Parallele Zeilenbebauung mit architektonischem Zeilengrün (1920er bis 1930er), 3 – 5-geschossig                6785
Wochenendhäuser und kleingartenartige Gebiete                                                                  6443
Großsiedlungen und Punkthochhäuser (1960er-1980er), 4–11-geschossig                                            6159
Entkernte Blockrandbebauung, Lückenschluss nach 1945                                                           5096
Dörfliche Mischbebauung                                                                                        3693
Gewerbe- und Industriegebiet, großflächiger Einzelhandel, geringe Bebauung                                     3474
Geschosswohnungsbau der 1990er Jahre und jünger (1990er bis heute)                                             3283
Brachfläche                                                                                                    2214
Mischbebauung, halboffener und offener Schuppenhof, 2-4-geschossig                                             2154
Dichte Blockbebauung, geschlossener Hinterhof (1870er-1918), 5-6-geschossig                                    2149
Kleingartenanlage allgemein                                                                                    1416
Mischgebiet ohne Wohngebietscharakter, geringe Bebauung                                                        1367
Krankenhaus                                                                                                     814
Heterogene, innerstädtische Mischbebauung, Lückenschluss nach 1945                                              646
Sicherheit und Ordnung                                                                                          583
Kindertagesstätte                                                                                               428
Name: count, dtype: int64

======================================================================
reporting_of_demolition
dtype: object
unique values: 2

reporting_of_demolition
not_reported    327227
reported            69
Name: count, dtype: int64

In [42]:
df["demolition_target"] = (
    df["reporting_of_demolition"] == "reported"
).astype("int8")

display(df["demolition_target"].value_counts())

demolition_target
0    327227
1        69
Name: count, dtype: int64

In [43]:
from scipy.stats import pointbiserialr

continuous_predictors = [
    "bldg_area",
    "bldg_volume",
    "energy_intensity_kwh_m3a",
    "pop_density_pressure_change",
    "pop_density_pressure_pct_change",
    "dominant_age_share",
    "dominant_age_midpoint",
    "weighted_average_construction_year",
    "weighted_average_age_2015",
    "dominant_age_2015",
    "age_distribution_range",
    "age_data_available",
    "density_change_available",
]

corr_rows = []

for col in continuous_predictors:
    valid = df[[col, "demolition_target"]].dropna()

    if valid[col].nunique() > 1:
        r, p = pointbiserialr(
            valid["demolition_target"],
            valid[col]
        )
    else:
        r, p = np.nan, np.nan

    corr_rows.append({
        "variable": col,
        "n": len(valid),
        "positive_cases_in_n": int(valid["demolition_target"].sum()),
        "correlation": r,
        "p_value": p,
        "missing": int(df[col].isna().sum())
    })

correlation_results = (
    pd.DataFrame(corr_rows)
    .sort_values(
        "correlation",
        key=lambda s: s.abs(),
        ascending=False
    )
)

display(correlation_results)

KeyError: "['age_data_available'] not in index"

In [44]:
df["age_data_available"] = (
    df["number_of_age_periods"].gt(0)
).astype("int8")

df["density_change_available"] = (
    df["pop_density_pressure_change"].notna()
).astype("int8")

display(
    df[
        [
            "age_data_available",
            "density_change_available"
        ]
    ].value_counts()
)

age_data_available  density_change_available
1                   1                           274460
0                   1                            36547
                    0                            13734
1                   0                             2555
Name: count, dtype: int64

In [45]:
from scipy.stats import pointbiserialr

continuous_predictors = [
    "bldg_area",
    "bldg_volume",
    "energy_intensity_kwh_m3a",
    "pop_density_pressure_change",
    "pop_density_pressure_pct_change",
    "dominant_age_share",
    "dominant_age_midpoint",
    "weighted_average_construction_year",
    "weighted_average_age_2015",
    "dominant_age_2015",
    "age_distribution_range",
    "age_data_available",
    "density_change_available",
]

corr_rows = []

for col in continuous_predictors:
    valid = df[[col, "demolition_target"]].dropna()

    if valid[col].nunique() > 1:
        r, p = pointbiserialr(
            valid["demolition_target"],
            valid[col]
        )
    else:
        r, p = np.nan, np.nan

    corr_rows.append({
        "variable": col,
        "n": len(valid),
        "positive_cases_in_n": int(valid["demolition_target"].sum()),
        "correlation": r,
        "p_value": p,
        "missing": int(df[col].isna().sum())
    })

correlation_results = (
    pd.DataFrame(corr_rows)
    .sort_values(
        "correlation",
        key=lambda s: s.abs(),
        ascending=False
    )
)

display(correlation_results)

,variable,n,positive_cases_in_n,correlation,p_value,missing
0,bldg_area,327296,69,0.047642,9.309565e-164,0
1,bldg_volume,327296,69,0.045169,2.177023e-147,0
11,age_data_available,327296,69,-0.018910,2.797153e-27,0
12,density_change_available,327296,69,-0.016032,4.635068e-20,0
2,energy_intensity_kwh_m3a,327296,69,0.014982,1.019314e-17,0
7,weighted_average_construction_year,277015,26,-0.008823,3.418153e-06,50281
8,weighted_average_age_2015,277015,26,0.008823,3.418153e-06,50281
6,dominant_age_midpoint,277015,26,-0.008214,1.538417e-05,50281
9,dominant_age_2015,277015,26,0.008214,1.538417e-05,50281
3,pop_density_pressure_change,311007,49,0.001638,3.609119e-01,16289
5,dominant_age_share,277015,26,0.001404,4.598171e-01,50281
10,age_distribution_range,277015,26,-0.000903,6.345644e-01,50281
4,pop_density_pressure_pct_change,309327,48,-0.000622,7.294823e-01,17969

In [46]:
df = df.drop(columns=["bldg_function"])

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 52)
['building_serial_id', 'bldg_gmlid', 'AGS', 'bldg_area', 'bldg_volume', 'BtySetID', 'BtyID', 'BtySig', 'id', 'gisid', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'typ', 'typklar', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [47]:
display(
    df[
        [
            "AGS",
            "BtySetID",
            "BtyID",
            "id",
            "gisid",
            "nwbz"
        ]
    ].nunique().sort_values().to_frame("unique_values")
)

          unique_values
AGS                   1
BtySetID              1
BtyID                11
nwbz              38288
id               327215
gisid            327215

In [48]:
df = df.drop(
    columns=[
        "AGS",
        "BtySetID",
        "id",
        "gisid"
    ]
)

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 48)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtyID', 'BtySig', 'typ_ist', 'typ_mod1', 'k2_w_l', 'nwbz', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'typ', 'typklar', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [49]:
df = df.drop(columns=["nwbz"])

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 47)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtyID', 'BtySig', 'typ_ist', 'typ_mod1', 'k2_w_l', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'x_bis_1900', 'x1901_1910', 'x1911_1920', 'x1921_1930', 'x1931_1940', 'x1941_1950', 'x1951_1960', 'x1961_1970', 'x1971_1980', 'x1981_1990', 'x1991_2000', 'x2001_2010', 'x2011_2015', 'ueberw_dekade_woh_neu', 'typ', 'typklar', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [50]:
raw_age_cols = [
    "x_bis_1900",
    "x1901_1910",
    "x1911_1920",
    "x1921_1930",
    "x1931_1940",
    "x1941_1950",
    "x1951_1960",
    "x1961_1970",
    "x1971_1980",
    "x1981_1990",
    "x1991_2000",
    "x2001_2010",
    "x2011_2015"
]

df = df.drop(columns=raw_age_cols)

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 34)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtyID', 'BtySig', 'typ_ist', 'typ_mod1', 'k2_w_l', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'ueberw_dekade_woh_neu', 'typ', 'typklar', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [51]:
drop_redundant_type_cols = [
    "BtyID",
    "ueberw_dekade_woh_neu",
    "typ_ist",
    "typ_mod1",
    "typ",
    "typklar"
]

df = df.drop(columns=drop_redundant_type_cols)

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 28)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtySig', 'k2_w_l', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [52]:
print("Shape:", df.shape)

for i, col in enumerate(df.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (327296, 28)
01. building_serial_id
02. bldg_gmlid
03. bldg_area
04. bldg_volume
05. BtySig
06. k2_w_l
07. energy_intensity_kwh_m3a
08. denkmal_status
09. freistehen
10. anderertyp
11. doppelhaus
12. gereihtes
13. pop_density_pressure_change
14. pop_density_pressure_pct_change
15. reporting_of_demolition
16. number_of_age_periods
17. dominant_age_share
18. dominant_age_period_label
19. dominant_age_midpoint
20. weighted_average_construction_year
21. weighted_average_age_2015
22. dominant_age_2015
23. earliest_age_midpoint
24. latest_age_midpoint
25. age_distribution_range
26. demolition_target
27. age_data_available
28. density_change_available

In [53]:
pd.crosstab(
    df["BtySig"],
    df["k2_w_l"],
    normalize="index"
).round(3)

k2_w_l,K01 - beheizt,K02 - temporär beheizt,K03 - geringe Raumsolltemperatur,K04 - teilweise beheizt,K05 - nicht beheizt,K06 - keine Beurteilung möglich (teilweise beheizte Gebäude in einem Gebäudekonglomerat),K07 - keine Beurteilung möglich (keine GFK-Zuordnung möglich),K08 - keine Beurteilung möglich (sonstige Gründe),K09 - nicht wärmerelevant (Grundfläche unter 50 qm),"K10 - Wohngebäude inkl. Mischnutzungen (nachrichtlich, ohne Beurteilung)"
BtySig,,,,,,,,,,
ASB,0.011,0.000,0.466,0.466,0.000,0.000,0.0,0.000,0.006,0.051
HOT,0.997,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.002,0.001
HSN,0.463,0.000,0.000,0.095,0.000,0.007,0.0,0.000,0.000,0.435
MFH,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,1.000
NAS,0.003,0.000,0.017,0.007,0.000,0.000,0.0,0.000,0.000,0.972
OFC,0.999,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000
ONR,0.784,0.048,0.109,0.046,0.001,0.010,0.0,0.000,0.001,0.001
PRO,0.090,0.001,0.787,0.114,0.000,0.000,0.0,0.003,0.003,0.003
SFH,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,1.000
STG,0.000,0.000,0.986,0.009,0.000,0.000,0.0,0.000,0.004,0.000
TRD,0.960,0.036,0.001,0.000,0.000,0.000,0.0,0.000,0.002,0.000

In [54]:
df = df.drop(columns=["k2_w_l"])

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 27)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtySig', 'energy_intensity_kwh_m3a', 'denkmal_status', 'freistehen', 'anderertyp', 'doppelhaus', 'gereihtes', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [55]:
df = df.drop(
    columns=[
        "freistehen",
        "anderertyp",
        "doppelhaus",
        "gereihtes"
    ]
)

print("New shape:", df.shape)
print(df.columns.tolist())

New shape: (327296, 23)
['building_serial_id', 'bldg_gmlid', 'bldg_area', 'bldg_volume', 'BtySig', 'energy_intensity_kwh_m3a', 'denkmal_status', 'pop_density_pressure_change', 'pop_density_pressure_pct_change', 'reporting_of_demolition', 'number_of_age_periods', 'dominant_age_share', 'dominant_age_period_label', 'dominant_age_midpoint', 'weighted_average_construction_year', 'weighted_average_age_2015', 'dominant_age_2015', 'earliest_age_midpoint', 'latest_age_midpoint', 'age_distribution_range', 'demolition_target', 'age_data_available', 'density_change_available']

In [56]:
demolition_reference = {
    "2022": 71,
    "2023": 75,
    "2024": 90,
    "2025": 73
}

reference_total = sum(demolition_reference.values())
observed_total = int(df["demolition_target"].sum())

demolition_expansion_factor = reference_total / observed_total

print("Reference total:", reference_total)
print("Observed reported total:", observed_total)
print("Expansion factor:", demolition_expansion_factor)

Reference total: 309
Observed reported total: 69
Expansion factor: 4.478260869565218

In [57]:
demolition_reference = {
    "2022": 71,
    "2023": 75,
    "2024": 90,
    "2025": 73
}

reference_total = sum(demolition_reference.values())
observed_total = int(df["demolition_target"].sum())

demolition_expansion_factor = reference_total / observed_total

print("Reference demolition total:", reference_total)
print("Observed reported cases:", observed_total)
print("Aggregate expansion factor:", round(demolition_expansion_factor, 4))

Reference demolition total: 309
Observed reported cases: 69
Aggregate expansion factor: 4.4783

In [58]:
bty_demolition_summary = (
    df.groupby("BtySig")
      .agg(
          total_buildings=("building_serial_id", "count"),
          reported_demolitions=("demolition_target", "sum")
      )
      .reset_index()
)

bty_demolition_summary["reporting_rate_per_1000"] = (
    bty_demolition_summary["reported_demolitions"]
    / bty_demolition_summary["total_buildings"]
    * 1000
)

bty_demolition_summary["share_of_reported_demolitions_pct"] = (
    bty_demolition_summary["reported_demolitions"]
    / bty_demolition_summary["reported_demolitions"].sum()
    * 100
)

bty_demolition_summary = bty_demolition_summary.sort_values(
    "reporting_rate_per_1000",
    ascending=False
)

bty_demolition_summary

,BtySig,total_buildings,reported_demolitions,reporting_rate_per_1000,share_of_reported_demolitions_pct
1,HOT,1350,6,4.444444,8.695652
10,TRD,4294,13,3.027480,18.840580
2,HSN,1359,3,2.207506,4.347826
6,ONR,8724,16,1.834021,23.188406
5,OFC,4759,8,1.681025,11.594203
7,PRO,7867,6,0.762680,8.695652
9,STG,4716,2,0.424088,2.898551
3,MFH,104852,14,0.133522,20.289855
8,SFH,172854,1,0.005785,1.449275
0,ASB,178,0,0.000000,0.000000
4,NAS,16343,0,0.000000,0.000000

In [59]:
btysig_labels = {
    "SFH": "Single-family houses",
    "MFH": "Multi-family houses",
    "HOT": "Hotels and restaurants",
    "HSN": "Hospitals",
    "ONR": "Other non-residential buildings",
    "OFC": "Offices",
    "TRD": "Trade buildings",
    "PRO": "Factories and workshops",
    "STG": "Storage buildings",
    "ASB": "Agricultural service buildings",
    "NAS": "Other non-agricultural service buildings"
}

bty_demolition_summary["building_type_name"] = (
    bty_demolition_summary["BtySig"].map(btysig_labels)
)

bty_demolition_summary = bty_demolition_summary[
    [
        "BtySig",
        "building_type_name",
        "total_buildings",
        "reported_demolitions",
        "reporting_rate_per_1000",
        "share_of_reported_demolitions_pct"
    ]
]

bty_demolition_summary

,BtySig,building_type_name,total_buildings,reported_demolitions,reporting_rate_per_1000,share_of_reported_demolitions_pct
1,HOT,Hotels and restaurants,1350,6,4.444444,8.695652
10,TRD,Trade buildings,4294,13,3.027480,18.840580
2,HSN,Hospitals,1359,3,2.207506,4.347826
6,ONR,Other non-residential buildings,8724,16,1.834021,23.188406
5,OFC,Offices,4759,8,1.681025,11.594203
7,PRO,Factories and workshops,7867,6,0.762680,8.695652
9,STG,Storage buildings,4716,2,0.424088,2.898551
3,MFH,Multi-family houses,104852,14,0.133522,20.289855
8,SFH,Single-family houses,172854,1,0.005785,1.449275
0,ASB,Agricultural service buildings,178,0,0.000000,0.000000
4,NAS,Other non-agricultural service buildings,16343,0,0.000000,0.000000

In [60]:
import numpy as np
import pandas as pd

z = 1.96  # 95% confidence level

ci_results = []

for _, row in bty_demolition_summary.iterrows():
    x = int(row["reported_demolitions"])
    n = int(row["total_buildings"])

    if n == 0:
        lower = np.nan
        upper = np.nan
    else:
        p = x / n

        denominator = 1 + (z**2 / n)

        centre = (
            p + (z**2 / (2 * n))
        ) / denominator

        margin = (
            z * np.sqrt(
                (p * (1 - p) / n)
                + (z**2 / (4 * n**2))
            )
        ) / denominator

        lower = centre - margin
        upper = centre + margin

    ci_results.append({
        "BtySig": row["BtySig"],
        "building_type_name": row["building_type_name"],
        "total_buildings": n,
        "reported_demolitions": x,
        "rate_per_1000": row["reporting_rate_per_1000"],
        "lower_ci_per_1000": lower * 1000,
        "upper_ci_per_1000": upper * 1000
    })

bty_rate_ci = pd.DataFrame(ci_results)

bty_rate_ci = bty_rate_ci.sort_values(
    "rate_per_1000",
    ascending=False
)

bty_rate_ci

,BtySig,building_type_name,total_buildings,reported_demolitions,rate_per_1000,lower_ci_per_1000,upper_ci_per_1000
0,HOT,Hotels and restaurants,1350,6,4.444444,2.038445e+00,9.662776
1,TRD,Trade buildings,4294,13,3.027480,1.770159e+00,5.173234
2,HSN,Hospitals,1359,3,2.207506,7.510153e-01,6.470367
3,ONR,Other non-residential buildings,8724,16,1.834021,1.129250e+00,2.977332
4,OFC,Offices,4759,8,1.681025,8.520449e-01,3.313872
5,PRO,Factories and workshops,7867,6,0.762680,3.495835e-01,1.663111
6,STG,Storage buildings,4716,2,0.424088,1.163056e-01,1.545106
7,MFH,Multi-family houses,104852,14,0.133522,7.954019e-02,0.224130
8,SFH,Single-family houses,172854,1,0.005785,1.021209e-03,0.032773
9,ASB,Agricultural service buildings,178,0,0.000000,0.000000e+00,21.126079
10,NAS,Other non-agricultural service buildings,16343,0,0.000000,-1.355253e-17,0.235006

In [61]:
bty_rate_ci["lower_ci_per_1000"] = (
    bty_rate_ci["lower_ci_per_1000"].clip(lower=0)
)

bty_rate_ci

,BtySig,building_type_name,total_buildings,reported_demolitions,rate_per_1000,lower_ci_per_1000,upper_ci_per_1000
0,HOT,Hotels and restaurants,1350,6,4.444444,2.038445,9.662776
1,TRD,Trade buildings,4294,13,3.027480,1.770159,5.173234
2,HSN,Hospitals,1359,3,2.207506,0.751015,6.470367
3,ONR,Other non-residential buildings,8724,16,1.834021,1.129250,2.977332
4,OFC,Offices,4759,8,1.681025,0.852045,3.313872
5,PRO,Factories and workshops,7867,6,0.762680,0.349584,1.663111
6,STG,Storage buildings,4716,2,0.424088,0.116306,1.545106
7,MFH,Multi-family houses,104852,14,0.133522,0.079540,0.224130
8,SFH,Single-family houses,172854,1,0.005785,0.001021,0.032773
9,ASB,Agricultural service buildings,178,0,0.000000,0.000000,21.126079
10,NAS,Other non-agricultural service buildings,16343,0,0.000000,0.000000,0.235006

In [62]:
comparison_cols = [
    "bldg_area",
    "bldg_volume",
    "energy_intensity_kwh_m3a",
    "pop_density_pressure_change",
    "pop_density_pressure_pct_change",
    "dominant_age_share",
    "dominant_age_midpoint",
    "weighted_average_construction_year",
    "weighted_average_age_2015",
    "age_distribution_range"
]

distribution_summary = (
    df.groupby("demolition_target")[comparison_cols]
      .agg(["count", "mean", "median", "min", "max"])
      .round(3)
)

distribution_summary

                  bldg_area                                      bldg_volume  \
                      count      mean   median     min       max       count
demolition_target
0                    327227   245.930   113.03    3.54  69736.13      327227
1                        69  2458.328  1030.60  131.63  29727.78          69

                                                            ...  \
                        mean    median     min         max  ...
demolition_target                                           ...
0                   3293.237    778.15    8.19  1812998.13  ...
1                  38285.939  13168.26  706.90   705763.64  ...

                  weighted_average_age_2015                               \
                                      count    mean  median   min    max
demolition_target
0                                    276989  56.312  52.500   2.0  125.0
1                                        26  78.177  80.556  30.0  117.5

                  age_distribution_range
                                   count    mean median  min    max
demolition_target
0                                 276989  74.369   80.0  0.0  123.0
1                                     26  71.346   75.0  0.0  115.0

[2 rows x 50 columns]

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327296 entries, 0 to 327295
Data columns (total 23 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   building_serial_id                  327296 non-null  int64
 1   bldg_gmlid                          327296 non-null  object
 2   bldg_area                           327296 non-null  float64
 3   bldg_volume                         327296 non-null  float64
 4   BtySig                              327296 non-null  object
 5   energy_intensity_kwh_m3a            327296 non-null  float64
 6   denkmal_status                      327296 non-null  bool
 7   pop_density_pressure_change         311007 non-null  float64
 8   pop_density_pressure_pct_change     309327 non-null  float64
 9   reporting_of_demolition             327296 non-null  object
 10  number_of_age_periods               327296 non-null  int64
 11  dominant_age_share                  277015 non-null  float64
 12  dominant_age_period_label           277015 non-null  object
 13  dominant_age_midpoint               277015 non-null  float64
 14  weighted_average_construction_year  277015 non-null  float64
 15  weighted_average_age_2015           277015 non-null  float64
 16  dominant_age_2015                   277015 non-null  float64
 17  earliest_age_midpoint               277015 non-null  float64
 18  latest_age_midpoint                 277015 non-null  float64
 19  age_distribution_range              277015 non-null  float64
 20  demolition_target                   327296 non-null  int8
 21  age_data_available                  327296 non-null  int8
 22  density_change_available            327296 non-null  int8
dtypes: bool(1), float64(13), int64(2), int8(3), object(4)
memory usage: 48.7+ MB

In [64]:
from pathlib import Path

output_dir = Path(r"C:\Users\deqin\osm_temporal_outputs")
output_dir.mkdir(parents=True, exist_ok=True)

matcad_attributes_csv = (
    output_dir / "MATCAD_Energy_Age_Denkmal_PopPressure_Abriss_attributes.csv"
)

df.to_csv(
    matcad_attributes_csv,
    index=False
)

print(f"Saved: {matcad_attributes_csv}")

Saved: C:\Users\deqin\osm_temporal_outputs\MATCAD_Energy_Age_Denkmal_PopPressure_Abriss_attributes.csv

In [ ]:
key_comparison_cols = [
    "bldg_area",
    "bldg_volume",
    "energy_intensity_kwh_m3a",
    "pop_density_pressure_change",
    "pop_density_pressure_pct_change",
    "dominant_age_share",
    "weighted_average_construction_year",
    "weighted_average_age_2015",
    "age_distribution_range"
]

compact_comparison = (
    df.groupby("demolition_target")[key_comparison_cols]
      .agg(["count", "mean", "median"])
      .round(2)
      .T
)

compact_comparison.columns = [
    "not_reported",
    "reported"
]

compact_comparison

In [ ]:
size_by_type = (
    df.groupby(["BtySig", "demolition_target"])[
        ["bldg_area", "bldg_volume", "energy_intensity_kwh_m3a"]
    ]
    .agg(["count", "median", "mean"])
    .round(2)
)

size_by_type

In [ ]:
size_ratio_summary = (
    df.groupby(["BtySig", "demolition_target"])[
        ["bldg_area", "bldg_volume"]
    ]
    .median()
    .unstack("demolition_target")
)

size_ratio_summary.columns = [
    f"{var}_{'not_reported' if target == 0 else 'reported'}"
    for var, target in size_ratio_summary.columns
]

size_ratio_summary["area_median_ratio"] = (
    size_ratio_summary["bldg_area_reported"]
    / size_ratio_summary["bldg_area_not_reported"]
)

size_ratio_summary["volume_median_ratio"] = (
    size_ratio_summary["bldg_volume_reported"]
    / size_ratio_summary["bldg_volume_not_reported"]
)

size_ratio_summary.sort_values(
    "area_median_ratio",
    ascending=False
)

In [ ]:
df["area_quantile"] = pd.qcut(
    df["bldg_area"],
    q=5,
    labels=[
        "Q1_smallest",
        "Q2",
        "Q3",
        "Q4",
        "Q5_largest"
    ],
    duplicates="drop"
)

area_quantile_summary = (
    df.groupby("area_quantile", observed=False)
      .agg(
          total_buildings=("building_serial_id", "count"),
          reported_demolitions=("demolition_target", "sum")
      )
      .reset_index()
)

area_quantile_summary["reporting_rate_per_1000"] = (
    area_quantile_summary["reported_demolitions"]
    / area_quantile_summary["total_buildings"]
    * 1000
)

area_quantile_summary

In [ ]:
df["volume_quantile"] = pd.qcut(
    df["bldg_volume"],
    q=5,
    labels=[
        "Q1_smallest",
        "Q2",
        "Q3",
        "Q4",
        "Q5_largest"
    ],
    duplicates="drop"
)

volume_quantile_summary = (
    df.groupby("volume_quantile", observed=False)
      .agg(
          total_buildings=("building_serial_id", "count"),
          reported_demolitions=("demolition_target", "sum")
      )
      .reset_index()
)

volume_quantile_summary["reporting_rate_per_1000"] = (
    volume_quantile_summary["reported_demolitions"]
    / volume_quantile_summary["total_buildings"]
    * 1000
)

volume_quantile_summary

In [ ]:
area_volume_corr = df[
    ["bldg_area", "bldg_volume"]
].corr()

area_volume_corr

In [ ]:
df["volume_area_ratio"] = (
    df["bldg_volume"] / df["bldg_area"]
)

df["volume_area_ratio"].describe()

In [ ]:
height_proxy_comparison = (
    df.groupby("demolition_target")["volume_area_ratio"]
      .agg(["count", "mean", "median", "std", "min", "max"])
      .round(3)
)

height_proxy_comparison

In [ ]:
df["height_proxy_quantile"] = pd.qcut(
    df["volume_area_ratio"],
    q=5,
    labels=[
        "Q1_lowest",
        "Q2",
        "Q3",
        "Q4",
        "Q5_highest"
    ],
    duplicates="drop"
)

height_quantile_summary = (
    df.groupby("height_proxy_quantile", observed=False)
      .agg(
          total_buildings=("building_serial_id", "count"),
          reported_demolitions=("demolition_target", "sum")
      )
      .reset_index()
)

height_quantile_summary["reporting_rate_per_1000"] = (
    height_quantile_summary["reported_demolitions"]
    / height_quantile_summary["total_buildings"]
    * 1000
)

height_quantile_summary

In [ ]:
df["area_size_group"] = pd.qcut(
    df["bldg_area"],
    q=3,
    labels=["small_area", "medium_area", "large_area"],
    duplicates="drop"
)

df["height_size_group"] = pd.qcut(
    df["volume_area_ratio"],
    q=3,
    labels=["low_height", "medium_height", "high_height"],
    duplicates="drop"
)

area_height_summary = (
    df.groupby(["area_size_group", "height_size_group"], observed=False)
      .agg(
          total_buildings=("building_serial_id", "count"),
          reported_demolitions=("demolition_target", "sum")
      )
      .reset_index()
)

area_height_summary["reporting_rate_per_1000"] = (
    area_height_summary["reported_demolitions"]
    / area_height_summary["total_buildings"]
    * 1000
)

area_height_summary

In [ ]:
temporary_analysis_cols = [
    "area_quantile",
    "volume_quantile",
    "height_proxy_quantile",
    "area_size_group",
    "height_size_group"
]

df = df.drop(columns=temporary_analysis_cols, errors="ignore")

df.shape, df.columns.tolist()

In [ ]:
missing_summary = (
    df.isna()
      .sum()
      .to_frame("missing_count")
)

missing_summary["missing_pct"] = (
    missing_summary["missing_count"] / len(df) * 100
).round(2)

missing_summary.sort_values("missing_count", ascending=False)